/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  VMwareRunAsAccount,
  RunAsAccountsGetAllRunAsAccountsInSiteOptionalParams,
  RunAsAccountsGetRunAsAccountOptionalParams,
  RunAsAccountsGetRunAsAccountResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a RunAsAccounts. */
export interface RunAsAccounts {
  /**
   * Method to get run as accounts.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  listAllRunAsAccountsInSite(
    resourceGroupName: string,
    siteName: string,
    options?: RunAsAccountsGetAllRunAsAccountsInSiteOptionalParams
  ): PagedAsyncIterableIterator<VMwareRunAsAccount>;
  /**
   * Method to get run as account.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param accountName Run as account ARM name.
   * @param options The options parameters.
   */
  getRunAsAccount(
    resourceGroupName: string,
    siteName: string,
    accountName: string,
    options?: RunAsAccountsGetRunAsAccountOptionalParams
  ): Promise<RunAsAccountsGetRunAsAccountResponse>;
}
