/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";
import * as coreRestPipeline from "@azure/core-rest-pipeline";
import {
  PipelineRequest,
  PipelineResponse,
  SendRequest
} from "@azure/core-rest-pipeline";
import * as coreAuth from "@azure/core-auth";
import {
  HyperVClusterOperationsImpl,
  HyperVHostOperationsImpl,
  HyperVJobsImpl,
  HyperVMachinesImpl,
  HyperVOperationsStatusImpl,
  HyperVRunAsAccountsImpl,
  HyperVSitesImpl,
  JobsImpl,
  MachinesImpl,
  RunAsAccountsImpl,
  SitesImpl,
  VCenterOperationsImpl,
  VMwareOperationsStatusImpl,
  MasterSitesImpl,
  OperationsImpl,
  PrivateEndpointConnectionOperationsImpl,
  PrivateLinkResourcesImpl,
  VMwareSitesImpl
} from "./operations";
import {
  HyperVClusterOperations,
  HyperVHostOperations,
  HyperVJobs,
  HyperVMachines,
  HyperVOperationsStatus,
  HyperVRunAsAccounts,
  HyperVSites,
  Jobs,
  Machines,
  RunAsAccounts,
  Sites,
  VCenterOperations,
  VMwareOperationsStatus,
  MasterSites,
  Operations,
  PrivateEndpointConnectionOperations,
  PrivateLinkResources,
  VMwareSites
} from "./operationsInterfaces";
import { AzureMigrateV2OptionalParams } from "./models";

export class AzureMigrateV2 extends coreClient.ServiceClient {
  $host: string;
  subscriptionId: string;
  apiVersion: string;

  /**
   * Initializes a new instance of the AzureMigrateV2 class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param subscriptionId Azure Subscription Id in which project was created.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    subscriptionId: string,
    options?: AzureMigrateV2OptionalParams
  ) {
    if (credentials === undefined) {
      throw new Error("'credentials' cannot be null");
    }
    if (subscriptionId === undefined) {
      throw new Error("'subscriptionId' cannot be null");
    }

    // Initializing default values for options
    if (!options) {
      options = {};
    }
    const defaults: AzureMigrateV2OptionalParams = {
      requestContentType: "application/json; charset=utf-8",
      credential: credentials
    };

    const packageDetails = `azsdk-js-arm-migrate/1.0.0-beta.1`;
    const userAgentPrefix =
      options.userAgentOptions && options.userAgentOptions.userAgentPrefix
        ? `${options.userAgentOptions.userAgentPrefix} ${packageDetails}`
        : `${packageDetails}`;

    const optionsWithDefaults = {
      ...defaults,
      ...options,
      userAgentOptions: {
        userAgentPrefix
      },
      endpoint:
        options.endpoint ?? options.baseUri ?? "https://management.azure.com"
    };
    super(optionsWithDefaults);

    let bearerTokenAuthenticationPolicyFound: boolean = false;
    if (options?.pipeline && options.pipeline.getOrderedPolicies().length > 0) {
      const pipelinePolicies: coreRestPipeline.PipelinePolicy[] = options.pipeline.getOrderedPolicies();
      bearerTokenAuthenticationPolicyFound = pipelinePolicies.some(
        (pipelinePolicy) =>
          pipelinePolicy.name ===
          coreRestPipeline.bearerTokenAuthenticationPolicyName
      );
    }
    if (
      !options ||
      !options.pipeline ||
      options.pipeline.getOrderedPolicies().length == 0 ||
      !bearerTokenAuthenticationPolicyFound
    ) {
      this.pipeline.removePolicy({
        name: coreRestPipeline.bearerTokenAuthenticationPolicyName
      });
      this.pipeline.addPolicy(
        coreRestPipeline.bearerTokenAuthenticationPolicy({
          credential: credentials,
          scopes:
            optionsWithDefaults.credentialScopes ??
            `${optionsWithDefaults.endpoint}/.default`,
          challengeCallbacks: {
            authorizeRequestOnChallenge:
              coreClient.authorizeRequestOnClaimChallenge
          }
        })
      );
    }
    // Parameter assignments
    this.subscriptionId = subscriptionId;

    // Assigning values to Constant parameters
    this.$host = options.$host || "https://management.azure.com";
    this.apiVersion = options.apiVersion || "2020-07-07";
    this.hyperVClusterOperations = new HyperVClusterOperationsImpl(this);
    this.hyperVHostOperations = new HyperVHostOperationsImpl(this);
    this.hyperVJobs = new HyperVJobsImpl(this);
    this.hyperVMachines = new HyperVMachinesImpl(this);
    this.hyperVOperationsStatus = new HyperVOperationsStatusImpl(this);
    this.hyperVRunAsAccounts = new HyperVRunAsAccountsImpl(this);
    this.hyperVSites = new HyperVSitesImpl(this);
    this.jobs = new JobsImpl(this);
    this.machines = new MachinesImpl(this);
    this.runAsAccounts = new RunAsAccountsImpl(this);
    this.sites = new SitesImpl(this);
    this.vCenterOperations = new VCenterOperationsImpl(this);
    this.vMwareOperationsStatus = new VMwareOperationsStatusImpl(this);
    this.masterSites = new MasterSitesImpl(this);
    this.operations = new OperationsImpl(this);
    this.privateEndpointConnectionOperations = new PrivateEndpointConnectionOperationsImpl(
      this
    );
    this.privateLinkResources = new PrivateLinkResourcesImpl(this);
    this.vMwareSites = new VMwareSitesImpl(this);
    this.addCustomApiVersionPolicy(options.apiVersion);
  }

  /** A function that adds a policy that sets the api-version (or equivalent) to reflect the library version. */
  private addCustomApiVersionPolicy(apiVersion?: string) {
    if (!apiVersion) {
      return;
    }
    const apiVersionPolicy = {
      name: "CustomApiVersionPolicy",
      async sendRequest(
        request: PipelineRequest,
        next: SendRequest
      ): Promise<PipelineResponse> {
        const param = request.url.split("?");
        if (param.length > 1) {
          const newParams = param[1].split("&").map((item) => {
            if (item.indexOf("api-version") > -1) {
              return "api-version=" + apiVersion;
            } else {
              return item;
            }
          });
          request.url = param[0] + "?" + newParams.join("&");
        }
        return next(request);
      }
    };
    this.pipeline.addPolicy(apiVersionPolicy);
  }

  hyperVClusterOperations: HyperVClusterOperations;
  hyperVHostOperations: HyperVHostOperations;
  hyperVJobs: HyperVJobs;
  hyperVMachines: HyperVMachines;
  hyperVOperationsStatus: HyperVOperationsStatus;
  hyperVRunAsAccounts: HyperVRunAsAccounts;
  hyperVSites: HyperVSites;
  jobs: Jobs;
  machines: Machines;
  runAsAccounts: RunAsAccounts;
  sites: Sites;
  vCenterOperations: VCenterOperations;
  vMwareOperationsStatus: VMwareOperationsStatus;
  masterSites: MasterSites;
  operations: Operations;
  privateEndpointConnectionOperations: PrivateEndpointConnectionOperations;
  privateLinkResources: PrivateLinkResources;
  vMwareSites: VMwareSites;
}
