/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  SourceControlConfiguration,
  SourceControlConfigurationsListByResourceGroupOptionalParams,
  SourceControlConfigurationsGetOptionalParams,
  SourceControlConfigurationsGetResponse,
  SourceControlConfigurationsCreateOrUpdateOptionalParams,
  SourceControlConfigurationsCreateOrUpdateResponse,
  SourceControlConfigurationsDeleteOptionalParams,
  SourceControlConfigurationsDeleteResponse,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a SourceControlConfigurations. */
export interface SourceControlConfigurations {
  /**
   * List all Source Control Configurations.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param options The options parameters.
   */
  listByResourceGroup(
    resourceGroupName: string,
    options?: SourceControlConfigurationsListByResourceGroupOptionalParams,
  ): PagedAsyncIterableIterator<SourceControlConfiguration>;
  /**
   * Gets details of the Source Control Configuration.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param sourceControlConfigurationName Name of the Source Control Configuration.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    sourceControlConfigurationName: string,
    options?: SourceControlConfigurationsGetOptionalParams,
  ): Promise<SourceControlConfigurationsGetResponse>;
  /**
   * Create a new Kubernetes Source Control Configuration.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param sourceControlConfigurationName Name of the Source Control Configuration.
   * @param resource Properties necessary to Create KubernetesConfiguration.
   * @param options The options parameters.
   */
  createOrUpdate(
    resourceGroupName: string,
    sourceControlConfigurationName: string,
    resource: SourceControlConfiguration,
    options?: SourceControlConfigurationsCreateOrUpdateOptionalParams,
  ): Promise<SourceControlConfigurationsCreateOrUpdateResponse>;
  /**
   * This will delete the YAML file used to set up the Source control configuration, thus stopping future
   * sync from the source repo.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param sourceControlConfigurationName Name of the Source Control Configuration.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    sourceControlConfigurationName: string,
    options?: SourceControlConfigurationsDeleteOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<SourceControlConfigurationsDeleteResponse>,
      SourceControlConfigurationsDeleteResponse
    >
  >;
  /**
   * This will delete the YAML file used to set up the Source control configuration, thus stopping future
   * sync from the source repo.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param sourceControlConfigurationName Name of the Source Control Configuration.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    sourceControlConfigurationName: string,
    options?: SourceControlConfigurationsDeleteOptionalParams,
  ): Promise<SourceControlConfigurationsDeleteResponse>;
}
