/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  WorkloadNetworkGateway,
  WorkloadNetworkGatewaysListByPrivateCloudOptionalParams,
  WorkloadNetworkGatewaysGetGatewayOptionalParams,
  WorkloadNetworkGatewaysGetGatewayResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a WorkloadNetworkGateways. */
export interface WorkloadNetworkGateways {
  /**
   * List of gateways in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param options The options parameters.
   */
  listByPrivateCloud(
    resourceGroupName: string,
    privateCloudName: string,
    options?: WorkloadNetworkGatewaysListByPrivateCloudOptionalParams
  ): PagedAsyncIterableIterator<WorkloadNetworkGateway>;
  /**
   * Get a gateway by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param gatewayId NSX Gateway identifier. Generally the same as the Gateway's display name
   * @param options The options parameters.
   */
  getGateway(
    resourceGroupName: string,
    privateCloudName: string,
    gatewayId: string,
    options?: WorkloadNetworkGatewaysGetGatewayOptionalParams
  ): Promise<WorkloadNetworkGatewaysGetGatewayResponse>;
}
