/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  WorkloadNetworkDnsService,
  WorkloadNetworkDnsServicesListByPrivateCloudOptionalParams,
  WorkloadNetworkDnsServicesGetDnsServiceOptionalParams,
  WorkloadNetworkDnsServicesGetDnsServiceResponse,
  WorkloadNetworkDnsServicesCreateDnsServiceOptionalParams,
  WorkloadNetworkDnsServicesCreateDnsServiceResponse,
  WorkloadNetworkDnsServiceUpdate,
  WorkloadNetworkDnsServicesUpdateDnsServiceOptionalParams,
  WorkloadNetworkDnsServicesUpdateDnsServiceResponse,
  WorkloadNetworkDnsServicesDeleteDnsServiceOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a WorkloadNetworkDnsServices. */
export interface WorkloadNetworkDnsServices {
  /**
   * List of DNS services in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param options The options parameters.
   */
  listByPrivateCloud(
    resourceGroupName: string,
    privateCloudName: string,
    options?: WorkloadNetworkDnsServicesListByPrivateCloudOptionalParams
  ): PagedAsyncIterableIterator<WorkloadNetworkDnsService>;
  /**
   * Get a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param options The options parameters.
   */
  getDnsService(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    options?: WorkloadNetworkDnsServicesGetDnsServiceOptionalParams
  ): Promise<WorkloadNetworkDnsServicesGetDnsServiceResponse>;
  /**
   * Create a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreateDnsService(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    resource: WorkloadNetworkDnsService,
    options?: WorkloadNetworkDnsServicesCreateDnsServiceOptionalParams
  ): Promise<
    SimplePollerLike<
      OperationState<WorkloadNetworkDnsServicesCreateDnsServiceResponse>,
      WorkloadNetworkDnsServicesCreateDnsServiceResponse
    >
  >;
  /**
   * Create a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreateDnsServiceAndWait(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    resource: WorkloadNetworkDnsService,
    options?: WorkloadNetworkDnsServicesCreateDnsServiceOptionalParams
  ): Promise<WorkloadNetworkDnsServicesCreateDnsServiceResponse>;
  /**
   * Create or update a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param properties The resource properties to be updated.
   * @param options The options parameters.
   */
  beginUpdateDnsService(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    properties: WorkloadNetworkDnsServiceUpdate,
    options?: WorkloadNetworkDnsServicesUpdateDnsServiceOptionalParams
  ): Promise<
    SimplePollerLike<
      OperationState<WorkloadNetworkDnsServicesUpdateDnsServiceResponse>,
      WorkloadNetworkDnsServicesUpdateDnsServiceResponse
    >
  >;
  /**
   * Create or update a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param properties The resource properties to be updated.
   * @param options The options parameters.
   */
  beginUpdateDnsServiceAndWait(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    properties: WorkloadNetworkDnsServiceUpdate,
    options?: WorkloadNetworkDnsServicesUpdateDnsServiceOptionalParams
  ): Promise<WorkloadNetworkDnsServicesUpdateDnsServiceResponse>;
  /**
   * Delete a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param options The options parameters.
   */
  beginDeleteDnsService(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    options?: WorkloadNetworkDnsServicesDeleteDnsServiceOptionalParams
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Delete a DNS service by id in a private cloud workload network.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param privateCloudName Name of the private cloud
   * @param dnsServiceId NSX DNS Service identifier. Generally the same as the DNS Service's display name
   * @param options The options parameters.
   */
  beginDeleteDnsServiceAndWait(
    resourceGroupName: string,
    privateCloudName: string,
    dnsServiceId: string,
    options?: WorkloadNetworkDnsServicesDeleteDnsServiceOptionalParams
  ): Promise<void>;
}
