# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
            
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/Oracle.Database/arm-Oracle.Database
      - sdk/Oracle.Database/ci.mgmt.yml

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/Oracle.Database/arm-Oracle.Database
      - sdk/Oracle.Database/ci.mgmt.yml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: Oracle.Database
    Artifacts:
      - name: azure-arm-Oracle.Database
        safeName: azurearmOracle.Database
        