/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";
import * as coreRestPipeline from "@azure/core-rest-pipeline";
import {
  PipelineRequest,
  PipelineResponse,
  SendRequest,
} from "@azure/core-rest-pipeline";
import * as coreAuth from "@azure/core-auth";
import {
  AdaptiveNetworkHardeningsImpl,
  AdvancedThreatProtectionImpl,
  AlertsImpl,
  AlertsSuppressionRulesImpl,
  AllowedConnectionsImpl,
  APICollectionsImpl,
  ApplicationsImpl,
  ApplicationOperationsImpl,
  SecurityConnectorApplicationsImpl,
  SecurityConnectorApplicationImpl,
  AdaptiveApplicationControlsImpl,
  AssessmentsMetadataImpl,
  AssessmentsImpl,
  AutomationsImpl,
  AutoProvisioningSettingsImpl,
  ComplianceResultsImpl,
  CompliancesImpl,
  ConnectorsImpl,
  CustomAssessmentAutomationsImpl,
  CustomEntityStoreAssignmentsImpl,
  DefenderForStorageImpl,
  DeviceSecurityGroupsImpl,
  DiscoveredSecuritySolutionsImpl,
  ExternalSecuritySolutionsImpl,
  GovernanceAssignmentsImpl,
  GovernanceRulesImpl,
  HealthReportsImpl,
  InformationProtectionPoliciesImpl,
  IotSecuritySolutionAnalyticsImpl,
  IotSecuritySolutionsAnalyticsAggregatedAlertImpl,
  IotSecuritySolutionsAnalyticsRecommendationImpl,
  IotSecuritySolutionImpl,
  JitNetworkAccessPoliciesImpl,
  LocationsImpl,
  MdeOnboardingsImpl,
  OperationsImpl,
  PricingsImpl,
  RegulatoryComplianceStandardsImpl,
  RegulatoryComplianceControlsImpl,
  RegulatoryComplianceAssessmentsImpl,
  SecureScoresImpl,
  SecureScoreControlsImpl,
  SecureScoreControlDefinitionsImpl,
  SecurityConnectorsImpl,
  AzureDevOpsOrgsImpl,
  AzureDevOpsProjectsImpl,
  AzureDevOpsReposImpl,
  DevOpsConfigurationsImpl,
  GitHubOwnersImpl,
  GitHubReposImpl,
  GitLabGroupsImpl,
  GitLabSubgroupsImpl,
  GitLabProjectsImpl,
  DevOpsOperationResultsImpl,
  SecurityContactsImpl,
  SecurityOperatorsImpl,
  SecuritySolutionsImpl,
  SecuritySolutionsReferenceDataOperationsImpl,
  SensitivitySettingsImpl,
  ServerVulnerabilityAssessmentOperationsImpl,
  ServerVulnerabilityAssessmentsSettingsImpl,
  SettingsImpl,
  SoftwareInventoriesImpl,
  SqlVulnerabilityAssessmentBaselineRulesImpl,
  SqlVulnerabilityAssessmentScansImpl,
  SqlVulnerabilityAssessmentScanResultsImpl,
  SubAssessmentsImpl,
  TasksImpl,
  TopologyImpl,
  WorkspaceSettingsImpl,
} from "./operations";
import {
  AdaptiveNetworkHardenings,
  AdvancedThreatProtection,
  Alerts,
  AlertsSuppressionRules,
  AllowedConnections,
  APICollections,
  Applications,
  ApplicationOperations,
  SecurityConnectorApplications,
  SecurityConnectorApplication,
  AdaptiveApplicationControls,
  AssessmentsMetadata,
  Assessments,
  Automations,
  AutoProvisioningSettings,
  ComplianceResults,
  Compliances,
  Connectors,
  CustomAssessmentAutomations,
  CustomEntityStoreAssignments,
  DefenderForStorage,
  DeviceSecurityGroups,
  DiscoveredSecuritySolutions,
  ExternalSecuritySolutions,
  GovernanceAssignments,
  GovernanceRules,
  HealthReports,
  InformationProtectionPolicies,
  IotSecuritySolutionAnalytics,
  IotSecuritySolutionsAnalyticsAggregatedAlert,
  IotSecuritySolutionsAnalyticsRecommendation,
  IotSecuritySolution,
  JitNetworkAccessPolicies,
  Locations,
  MdeOnboardings,
  Operations,
  Pricings,
  RegulatoryComplianceStandards,
  RegulatoryComplianceControls,
  RegulatoryComplianceAssessments,
  SecureScores,
  SecureScoreControls,
  SecureScoreControlDefinitions,
  SecurityConnectors,
  AzureDevOpsOrgs,
  AzureDevOpsProjects,
  AzureDevOpsRepos,
  DevOpsConfigurations,
  GitHubOwners,
  GitHubRepos,
  GitLabGroups,
  GitLabSubgroups,
  GitLabProjects,
  DevOpsOperationResults,
  SecurityContacts,
  SecurityOperators,
  SecuritySolutions,
  SecuritySolutionsReferenceDataOperations,
  SensitivitySettings,
  ServerVulnerabilityAssessmentOperations,
  ServerVulnerabilityAssessmentsSettings,
  Settings,
  SoftwareInventories,
  SqlVulnerabilityAssessmentBaselineRules,
  SqlVulnerabilityAssessmentScans,
  SqlVulnerabilityAssessmentScanResults,
  SubAssessments,
  Tasks,
  Topology,
  WorkspaceSettings,
} from "./operationsInterfaces";
import { SecurityCenterOptionalParams } from "./models";

export class SecurityCenter extends coreClient.ServiceClient {
  $host: string;
  subscriptionId?: string;
  apiVersion: string;

  /**
   * Initializes a new instance of the SecurityCenter class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param subscriptionId Azure subscription ID
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    subscriptionId: string,
    options?: SecurityCenterOptionalParams,
  );
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: SecurityCenterOptionalParams,
  );
  constructor(
    credentials: coreAuth.TokenCredential,
    subscriptionIdOrOptions?: SecurityCenterOptionalParams | string,
    options?: SecurityCenterOptionalParams,
  ) {
    if (credentials === undefined) {
      throw new Error("'credentials' cannot be null");
    }

    let subscriptionId: string | undefined;

    if (typeof subscriptionIdOrOptions === "string") {
      subscriptionId = subscriptionIdOrOptions;
    } else if (typeof subscriptionIdOrOptions === "object") {
      options = subscriptionIdOrOptions;
    }

    // Initializing default values for options
    if (!options) {
      options = {};
    }
    const defaults: SecurityCenterOptionalParams = {
      requestContentType: "application/json; charset=utf-8",
      credential: credentials,
    };

    const packageDetails = `azsdk-js-arm-security/6.0.0-beta.5`;
    const userAgentPrefix =
      options.userAgentOptions && options.userAgentOptions.userAgentPrefix
        ? `${options.userAgentOptions.userAgentPrefix} ${packageDetails}`
        : `${packageDetails}`;

    const optionsWithDefaults = {
      ...defaults,
      ...options,
      userAgentOptions: {
        userAgentPrefix,
      },
      endpoint:
        options.endpoint ?? options.baseUri ?? "https://management.azure.com",
    };
    super(optionsWithDefaults);

    let bearerTokenAuthenticationPolicyFound: boolean = false;
    if (options?.pipeline && options.pipeline.getOrderedPolicies().length > 0) {
      const pipelinePolicies: coreRestPipeline.PipelinePolicy[] =
        options.pipeline.getOrderedPolicies();
      bearerTokenAuthenticationPolicyFound = pipelinePolicies.some(
        (pipelinePolicy) =>
          pipelinePolicy.name ===
          coreRestPipeline.bearerTokenAuthenticationPolicyName,
      );
    }
    if (
      !options ||
      !options.pipeline ||
      options.pipeline.getOrderedPolicies().length == 0 ||
      !bearerTokenAuthenticationPolicyFound
    ) {
      this.pipeline.removePolicy({
        name: coreRestPipeline.bearerTokenAuthenticationPolicyName,
      });
      this.pipeline.addPolicy(
        coreRestPipeline.bearerTokenAuthenticationPolicy({
          credential: credentials,
          scopes:
            optionsWithDefaults.credentialScopes ??
            `${optionsWithDefaults.endpoint}/.default`,
          challengeCallbacks: {
            authorizeRequestOnChallenge:
              coreClient.authorizeRequestOnClaimChallenge,
          },
        }),
      );
    }
    // Parameter assignments
    this.subscriptionId = subscriptionId;

    // Assigning values to Constant parameters
    this.$host = options.$host || "https://management.azure.com";
    this.apiVersion = options.apiVersion || "2024-05-01-preview";
    this.adaptiveNetworkHardenings = new AdaptiveNetworkHardeningsImpl(this);
    this.advancedThreatProtection = new AdvancedThreatProtectionImpl(this);
    this.alerts = new AlertsImpl(this);
    this.alertsSuppressionRules = new AlertsSuppressionRulesImpl(this);
    this.allowedConnections = new AllowedConnectionsImpl(this);
    this.aPICollections = new APICollectionsImpl(this);
    this.applications = new ApplicationsImpl(this);
    this.applicationOperations = new ApplicationOperationsImpl(this);
    this.securityConnectorApplications = new SecurityConnectorApplicationsImpl(
      this,
    );
    this.securityConnectorApplication = new SecurityConnectorApplicationImpl(
      this,
    );
    this.adaptiveApplicationControls = new AdaptiveApplicationControlsImpl(
      this,
    );
    this.assessmentsMetadata = new AssessmentsMetadataImpl(this);
    this.assessments = new AssessmentsImpl(this);
    this.automations = new AutomationsImpl(this);
    this.autoProvisioningSettings = new AutoProvisioningSettingsImpl(this);
    this.complianceResults = new ComplianceResultsImpl(this);
    this.compliances = new CompliancesImpl(this);
    this.connectors = new ConnectorsImpl(this);
    this.customAssessmentAutomations = new CustomAssessmentAutomationsImpl(
      this,
    );
    this.customEntityStoreAssignments = new CustomEntityStoreAssignmentsImpl(
      this,
    );
    this.defenderForStorage = new DefenderForStorageImpl(this);
    this.deviceSecurityGroups = new DeviceSecurityGroupsImpl(this);
    this.discoveredSecuritySolutions = new DiscoveredSecuritySolutionsImpl(
      this,
    );
    this.externalSecuritySolutions = new ExternalSecuritySolutionsImpl(this);
    this.governanceAssignments = new GovernanceAssignmentsImpl(this);
    this.governanceRules = new GovernanceRulesImpl(this);
    this.healthReports = new HealthReportsImpl(this);
    this.informationProtectionPolicies = new InformationProtectionPoliciesImpl(
      this,
    );
    this.iotSecuritySolutionAnalytics = new IotSecuritySolutionAnalyticsImpl(
      this,
    );
    this.iotSecuritySolutionsAnalyticsAggregatedAlert =
      new IotSecuritySolutionsAnalyticsAggregatedAlertImpl(this);
    this.iotSecuritySolutionsAnalyticsRecommendation =
      new IotSecuritySolutionsAnalyticsRecommendationImpl(this);
    this.iotSecuritySolution = new IotSecuritySolutionImpl(this);
    this.jitNetworkAccessPolicies = new JitNetworkAccessPoliciesImpl(this);
    this.locations = new LocationsImpl(this);
    this.mdeOnboardings = new MdeOnboardingsImpl(this);
    this.operations = new OperationsImpl(this);
    this.pricings = new PricingsImpl(this);
    this.regulatoryComplianceStandards = new RegulatoryComplianceStandardsImpl(
      this,
    );
    this.regulatoryComplianceControls = new RegulatoryComplianceControlsImpl(
      this,
    );
    this.regulatoryComplianceAssessments =
      new RegulatoryComplianceAssessmentsImpl(this);
    this.secureScores = new SecureScoresImpl(this);
    this.secureScoreControls = new SecureScoreControlsImpl(this);
    this.secureScoreControlDefinitions = new SecureScoreControlDefinitionsImpl(
      this,
    );
    this.securityConnectors = new SecurityConnectorsImpl(this);
    this.azureDevOpsOrgs = new AzureDevOpsOrgsImpl(this);
    this.azureDevOpsProjects = new AzureDevOpsProjectsImpl(this);
    this.azureDevOpsRepos = new AzureDevOpsReposImpl(this);
    this.devOpsConfigurations = new DevOpsConfigurationsImpl(this);
    this.gitHubOwners = new GitHubOwnersImpl(this);
    this.gitHubRepos = new GitHubReposImpl(this);
    this.gitLabGroups = new GitLabGroupsImpl(this);
    this.gitLabSubgroups = new GitLabSubgroupsImpl(this);
    this.gitLabProjects = new GitLabProjectsImpl(this);
    this.devOpsOperationResults = new DevOpsOperationResultsImpl(this);
    this.securityContacts = new SecurityContactsImpl(this);
    this.securityOperators = new SecurityOperatorsImpl(this);
    this.securitySolutions = new SecuritySolutionsImpl(this);
    this.securitySolutionsReferenceDataOperations =
      new SecuritySolutionsReferenceDataOperationsImpl(this);
    this.sensitivitySettings = new SensitivitySettingsImpl(this);
    this.serverVulnerabilityAssessmentOperations =
      new ServerVulnerabilityAssessmentOperationsImpl(this);
    this.serverVulnerabilityAssessmentsSettings =
      new ServerVulnerabilityAssessmentsSettingsImpl(this);
    this.settings = new SettingsImpl(this);
    this.softwareInventories = new SoftwareInventoriesImpl(this);
    this.sqlVulnerabilityAssessmentBaselineRules =
      new SqlVulnerabilityAssessmentBaselineRulesImpl(this);
    this.sqlVulnerabilityAssessmentScans =
      new SqlVulnerabilityAssessmentScansImpl(this);
    this.sqlVulnerabilityAssessmentScanResults =
      new SqlVulnerabilityAssessmentScanResultsImpl(this);
    this.subAssessments = new SubAssessmentsImpl(this);
    this.tasks = new TasksImpl(this);
    this.topology = new TopologyImpl(this);
    this.workspaceSettings = new WorkspaceSettingsImpl(this);
    this.addCustomApiVersionPolicy(options.apiVersion);
  }

  /** A function that adds a policy that sets the api-version (or equivalent) to reflect the library version. */
  private addCustomApiVersionPolicy(apiVersion?: string) {
    if (!apiVersion) {
      return;
    }
    const apiVersionPolicy = {
      name: "CustomApiVersionPolicy",
      async sendRequest(
        request: PipelineRequest,
        next: SendRequest,
      ): Promise<PipelineResponse> {
        const param = request.url.split("?");
        if (param.length > 1) {
          const newParams = param[1].split("&").map((item) => {
            if (item.indexOf("api-version") > -1) {
              return "api-version=" + apiVersion;
            } else {
              return item;
            }
          });
          request.url = param[0] + "?" + newParams.join("&");
        }
        return next(request);
      },
    };
    this.pipeline.addPolicy(apiVersionPolicy);
  }

  adaptiveNetworkHardenings: AdaptiveNetworkHardenings;
  advancedThreatProtection: AdvancedThreatProtection;
  alerts: Alerts;
  alertsSuppressionRules: AlertsSuppressionRules;
  allowedConnections: AllowedConnections;
  aPICollections: APICollections;
  applications: Applications;
  applicationOperations: ApplicationOperations;
  securityConnectorApplications: SecurityConnectorApplications;
  securityConnectorApplication: SecurityConnectorApplication;
  adaptiveApplicationControls: AdaptiveApplicationControls;
  assessmentsMetadata: AssessmentsMetadata;
  assessments: Assessments;
  automations: Automations;
  autoProvisioningSettings: AutoProvisioningSettings;
  complianceResults: ComplianceResults;
  compliances: Compliances;
  connectors: Connectors;
  customAssessmentAutomations: CustomAssessmentAutomations;
  customEntityStoreAssignments: CustomEntityStoreAssignments;
  defenderForStorage: DefenderForStorage;
  deviceSecurityGroups: DeviceSecurityGroups;
  discoveredSecuritySolutions: DiscoveredSecuritySolutions;
  externalSecuritySolutions: ExternalSecuritySolutions;
  governanceAssignments: GovernanceAssignments;
  governanceRules: GovernanceRules;
  healthReports: HealthReports;
  informationProtectionPolicies: InformationProtectionPolicies;
  iotSecuritySolutionAnalytics: IotSecuritySolutionAnalytics;
  iotSecuritySolutionsAnalyticsAggregatedAlert: IotSecuritySolutionsAnalyticsAggregatedAlert;
  iotSecuritySolutionsAnalyticsRecommendation: IotSecuritySolutionsAnalyticsRecommendation;
  iotSecuritySolution: IotSecuritySolution;
  jitNetworkAccessPolicies: JitNetworkAccessPolicies;
  locations: Locations;
  mdeOnboardings: MdeOnboardings;
  operations: Operations;
  pricings: Pricings;
  regulatoryComplianceStandards: RegulatoryComplianceStandards;
  regulatoryComplianceControls: RegulatoryComplianceControls;
  regulatoryComplianceAssessments: RegulatoryComplianceAssessments;
  secureScores: SecureScores;
  secureScoreControls: SecureScoreControls;
  secureScoreControlDefinitions: SecureScoreControlDefinitions;
  securityConnectors: SecurityConnectors;
  azureDevOpsOrgs: AzureDevOpsOrgs;
  azureDevOpsProjects: AzureDevOpsProjects;
  azureDevOpsRepos: AzureDevOpsRepos;
  devOpsConfigurations: DevOpsConfigurations;
  gitHubOwners: GitHubOwners;
  gitHubRepos: GitHubRepos;
  gitLabGroups: GitLabGroups;
  gitLabSubgroups: GitLabSubgroups;
  gitLabProjects: GitLabProjects;
  devOpsOperationResults: DevOpsOperationResults;
  securityContacts: SecurityContacts;
  securityOperators: SecurityOperators;
  securitySolutions: SecuritySolutions;
  securitySolutionsReferenceDataOperations: SecuritySolutionsReferenceDataOperations;
  sensitivitySettings: SensitivitySettings;
  serverVulnerabilityAssessmentOperations: ServerVulnerabilityAssessmentOperations;
  serverVulnerabilityAssessmentsSettings: ServerVulnerabilityAssessmentsSettings;
  settings: Settings;
  softwareInventories: SoftwareInventories;
  sqlVulnerabilityAssessmentBaselineRules: SqlVulnerabilityAssessmentBaselineRules;
  sqlVulnerabilityAssessmentScans: SqlVulnerabilityAssessmentScans;
  sqlVulnerabilityAssessmentScanResults: SqlVulnerabilityAssessmentScanResults;
  subAssessments: SubAssessments;
  tasks: Tasks;
  topology: Topology;
  workspaceSettings: WorkspaceSettings;
}
