# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/batch/
    exclude:
      - sdk/batch/ci.mgmt.yml
      - sdk/batch/arm-batch
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/batch/
    exclude:
      - sdk/batch/ci.mgmt.yml
      - sdk/batch/arm-batch
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: batch
    Artifacts:
      - name: azure-rest-batch
        safeName: azurerestbatch
