/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationParameter,
  OperationURLParameter,
  OperationQueryParameter,
} from "@azure/core-client";
import {
  Extension as ExtensionMapper,
  ExtensionUpdate as ExtensionUpdateMapper,
  FluxConfiguration as FluxConfigurationMapper,
  FluxConfigurationUpdate as FluxConfigurationUpdateMapper,
  SourceControlConfiguration as SourceControlConfigurationMapper,
} from "../models/mappers";

export const accept: OperationParameter = {
  parameterPath: "accept",
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Accept",
    type: {
      name: "String",
    },
  },
};

export const $host: OperationURLParameter = {
  parameterPath: "$host",
  mapper: {
    serializedName: "$host",
    required: true,
    type: {
      name: "String",
    },
  },
  skipEncoding: true,
};

export const apiVersion: OperationQueryParameter = {
  parameterPath: "apiVersion",
  mapper: {
    defaultValue: "2024-06-01-preview",
    isConstant: true,
    serializedName: "api-version",
    type: {
      name: "String",
    },
  },
};

export const nextLink: OperationURLParameter = {
  parameterPath: "nextLink",
  mapper: {
    serializedName: "nextLink",
    required: true,
    type: {
      name: "String",
    },
  },
  skipEncoding: true,
};

export const subscriptionId: OperationURLParameter = {
  parameterPath: "subscriptionId",
  mapper: {
    serializedName: "subscriptionId",
    required: true,
    type: {
      name: "Uuid",
    },
  },
};

export const resourceGroupName: OperationURLParameter = {
  parameterPath: "resourceGroupName",
  mapper: {
    constraints: {
      MaxLength: 90,
      MinLength: 1,
    },
    serializedName: "resourceGroupName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const clusterRp: OperationURLParameter = {
  parameterPath: "clusterRp",
  mapper: {
    serializedName: "clusterRp",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const clusterResourceName: OperationURLParameter = {
  parameterPath: "clusterResourceName",
  mapper: {
    serializedName: "clusterResourceName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const clusterName: OperationURLParameter = {
  parameterPath: "clusterName",
  mapper: {
    serializedName: "clusterName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const extensionName: OperationURLParameter = {
  parameterPath: "extensionName",
  mapper: {
    constraints: {
      Pattern: new RegExp("[^]*"),
    },
    serializedName: "extensionName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const contentType: OperationParameter = {
  parameterPath: ["options", "contentType"],
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Content-Type",
    type: {
      name: "String",
    },
  },
};

export const resource: OperationParameter = {
  parameterPath: "resource",
  mapper: ExtensionMapper,
};

export const properties: OperationParameter = {
  parameterPath: "properties",
  mapper: ExtensionUpdateMapper,
};

export const forceDelete: OperationQueryParameter = {
  parameterPath: ["options", "forceDelete"],
  mapper: {
    serializedName: "forceDelete",
    type: {
      name: "Boolean",
    },
  },
};

export const body: OperationParameter = {
  parameterPath: "body",
  mapper: {
    serializedName: "body",
    required: true,
    type: {
      name: "Dictionary",
      value: { type: { name: "any" } },
    },
  },
};

export const operationId: OperationURLParameter = {
  parameterPath: "operationId",
  mapper: {
    serializedName: "operationId",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const fluxConfigurationName: OperationURLParameter = {
  parameterPath: "fluxConfigurationName",
  mapper: {
    constraints: {
      Pattern: new RegExp("[^]*"),
    },
    serializedName: "fluxConfigurationName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const resource1: OperationParameter = {
  parameterPath: "resource",
  mapper: FluxConfigurationMapper,
};

export const properties1: OperationParameter = {
  parameterPath: "properties",
  mapper: FluxConfigurationUpdateMapper,
};

export const sourceControlConfigurationName: OperationURLParameter = {
  parameterPath: "sourceControlConfigurationName",
  mapper: {
    constraints: {
      Pattern: new RegExp("[^]*"),
    },
    serializedName: "sourceControlConfigurationName",
    required: true,
    type: {
      name: "String",
    },
  },
};

export const resource2: OperationParameter = {
  parameterPath: "resource",
  mapper: SourceControlConfigurationMapper,
};
