/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  AzureAgFoodPlatformRPServicePrivateEndpointConnection,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsListByDataManagerForAgricultureOptionalParams,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsGetOptionalParams,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsGetResponse,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsCreateOrUpdateOptionalParams,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsCreateOrUpdateResponse,
  AzureAgFoodPlatformRpServicePrivateEndpointConnectionsDeleteOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a AzureAgFoodPlatformRpServicePrivateEndpointConnections. */
export interface AzureAgFoodPlatformRpServicePrivateEndpointConnections {
  /**
   * Get list of Private endpoint connections.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param dataManagerForAgricultureResourceName DataManagerForAgriculture resource name.
   * @param options The options parameters.
   */
  listByDataManagerForAgriculture(
    resourceGroupName: string,
    dataManagerForAgricultureResourceName: string,
    options?: AzureAgFoodPlatformRpServicePrivateEndpointConnectionsListByDataManagerForAgricultureOptionalParams
  ): PagedAsyncIterableIterator<
    AzureAgFoodPlatformRPServicePrivateEndpointConnection
  >;
  /**
   * Get Private endpoint connection object.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param dataManagerForAgricultureResourceName DataManagerForAgriculture resource name.
   * @param privateEndpointConnectionName Private endpoint connection name.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    dataManagerForAgricultureResourceName: string,
    privateEndpointConnectionName: string,
    options?: AzureAgFoodPlatformRpServicePrivateEndpointConnectionsGetOptionalParams
  ): Promise<AzureAgFoodPlatformRpServicePrivateEndpointConnectionsGetResponse>;
  /**
   * Approves or Rejects a Private endpoint connection request.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param dataManagerForAgricultureResourceName DataManagerForAgriculture resource name.
   * @param privateEndpointConnectionName Private endpoint connection name.
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  createOrUpdate(
    resourceGroupName: string,
    dataManagerForAgricultureResourceName: string,
    privateEndpointConnectionName: string,
    resource: AzureAgFoodPlatformRPServicePrivateEndpointConnection,
    options?: AzureAgFoodPlatformRpServicePrivateEndpointConnectionsCreateOrUpdateOptionalParams
  ): Promise<
    AzureAgFoodPlatformRpServicePrivateEndpointConnectionsCreateOrUpdateResponse
  >;
  /**
   * Delete Private endpoint connection request.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param dataManagerForAgricultureResourceName DataManagerForAgriculture resource name.
   * @param privateEndpointConnectionName Private endpoint connection name.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    dataManagerForAgricultureResourceName: string,
    privateEndpointConnectionName: string,
    options?: AzureAgFoodPlatformRpServicePrivateEndpointConnectionsDeleteOptionalParams
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Delete Private endpoint connection request.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param dataManagerForAgricultureResourceName DataManagerForAgriculture resource name.
   * @param privateEndpointConnectionName Private endpoint connection name.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    dataManagerForAgricultureResourceName: string,
    privateEndpointConnectionName: string,
    options?: AzureAgFoodPlatformRpServicePrivateEndpointConnectionsDeleteOptionalParams
  ): Promise<void>;
}
