/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  Cluster,
  RedisEnterpriseListBySubscriptionOptionalParams,
  RedisEnterpriseListByResourceGroupOptionalParams,
  RedisEnterpriseGetOptionalParams,
  RedisEnterpriseGetResponse,
  RedisEnterpriseCreateOptionalParams,
  RedisEnterpriseCreateResponse,
  ClusterUpdate,
  RedisEnterpriseUpdateOptionalParams,
  RedisEnterpriseUpdateResponse,
  RedisEnterpriseDeleteOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a RedisEnterprise. */
export interface RedisEnterprise {
  /**
   * Lists all RedisEnterprise clusters in a subscription.
   * @param options The options parameters.
   */
  listBySubscription(
    options?: RedisEnterpriseListBySubscriptionOptionalParams
  ): PagedAsyncIterableIterator<Cluster>;
  /**
   * Lists all RedisEnterprise clusters in a resource group.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param options The options parameters.
   */
  listByResourceGroup(
    resourceGroupName: string,
    options?: RedisEnterpriseListByResourceGroupOptionalParams
  ): PagedAsyncIterableIterator<Cluster>;
  /**
   * Gets information about a RedisEnterprise cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    clusterName: string,
    options?: RedisEnterpriseGetOptionalParams
  ): Promise<RedisEnterpriseGetResponse>;
  /**
   * Creates a RedisEnterprise cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreate(
    resourceGroupName: string,
    clusterName: string,
    resource: Cluster,
    options?: RedisEnterpriseCreateOptionalParams
  ): Promise<
    SimplePollerLike<
      OperationState<RedisEnterpriseCreateResponse>,
      RedisEnterpriseCreateResponse
    >
  >;
  /**
   * Creates a RedisEnterprise cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreateAndWait(
    resourceGroupName: string,
    clusterName: string,
    resource: Cluster,
    options?: RedisEnterpriseCreateOptionalParams
  ): Promise<RedisEnterpriseCreateResponse>;
  /**
   * Updates a RedisEnterprise cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param properties The resource properties to be updated.
   * @param options The options parameters.
   */
  beginUpdate(
    resourceGroupName: string,
    clusterName: string,
    properties: ClusterUpdate,
    options?: RedisEnterpriseUpdateOptionalParams
  ): Promise<
    SimplePollerLike<
      OperationState<RedisEnterpriseUpdateResponse>,
      RedisEnterpriseUpdateResponse
    >
  >;
  /**
   * Updates a RedisEnterprise cluster
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param properties The resource properties to be updated.
   * @param options The options parameters.
   */
  beginUpdateAndWait(
    resourceGroupName: string,
    clusterName: string,
    properties: ClusterUpdate,
    options?: RedisEnterpriseUpdateOptionalParams
  ): Promise<RedisEnterpriseUpdateResponse>;
  /**
   * Deletes a RedisEnterprise cluster and its databases
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    clusterName: string,
    options?: RedisEnterpriseDeleteOptionalParams
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Deletes a RedisEnterprise cluster and its databases
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param clusterName Name of cluster
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    clusterName: string,
    options?: RedisEnterpriseDeleteOptionalParams
  ): Promise<void>;
}
